# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout


      - setup_remote_docker

      - run:
          name: Docker build
          command: docker build -t oesteban/test_inc:latest .

      # run tests!
      - run:
          name: Run test
          command: docker run -ti oesteban/test_inc:latest 6

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - deploy:
          name: Push release
          timeout: 1000
          command: |
            if [[ "${CIRCLE_TAG}" != "" ]] && [[ "${DOCKER_PASS}" != "" ]]; then
                docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
                docker tag oesteban/test_inc oesteban/test_inc:$CIRCLE_TAG
                docker push oesteban/test_inc:$CIRCLE_TAG
                docker push oesteban/test_inc:latest
            fi

